### ISSUE TITLE
遇到了错误

### ISSUE THREAD

**Issue by BitmapLong** [yangzhongke/Zack.DotNetTrimmer#21]
执行命令
Zack.DotNetTrimmer.exe --greedy --file "E:\\me\\code\\C#\\xxxx\\bin\\Release\\net8.0-windows\\publish\\win-x86\\xxx.exe" "E:\\me\\code\\C#\\xxxx.cs"

报错信息如下：

Version:2.0.0.2(Microsoft Windows NT 10.0.19045.0)
Entering Direct Mode.
Press Ctrl+C or Ctrl+Break to terminate the application to be trimmed.
Error encountered while processing events:System.Exception: Read past end of stream.
   at FastSerialization.IOStreamStreamReader.Fill(Int32 minimum)
   at FastSerialization.MemoryStreamReader.ReadByte()
   at FastSerialization.Deserializer.ReadObject()
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
   at Zack.DotNetTrimmerLib.Trimmer.RunApp(String startupFile, RecordFileInfo recordFileInfo) in E:\主同步盘\我的坚果云\MyCode\DOTNET\Zack.DotNetTrimmer\Zack.DotNetTrimmerLib\Trimmer.cs:line 152

**Comment by yangzhongke** [comment]
不是在被裁剪的程序上按Ctrl+C，而是要在运行Zack.DotNetTrimmer.exe 的控制台中按Ctrl+C
