### ISSUE TITLE
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')

### ISSUE THREAD

**Issue by toolgood** [yangzhongke/Zack.DotNetTrimmer#9]
Zack.DotNetTrimmer.exe DevTest.exe
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String )
   at System.IO.DirectoryInfo..ctor(String )
   at Zack.DotNetTrimmerLib.BackupHelper.CopyDirectory(String sourceDir, String destinationDir, Boolean recursive) in E:\主同步盘\我的坚果云\MyCode\DOTNET\Zack.DotNetTrimmer\Zack.DotNetTrimmerLib\BackupHelper.cs:line 17
   at Zack.DotNetTrimmerLib.BackupHelper.BackupProject(String startupFile) in E:\主同步盘\我的坚果云\MyCode\DOTNET\Zack.DotNetTrimmer\Zack.DotNetTrimmerLib\BackupHelper.cs:line 8
   at Program.<Main>$(String[] args) in E:\主同步盘\我的坚果云\MyCode\DOTNET\Zack.DotNetTrimmer\Zack.DotNetTrimmer\Program.cs:line 25

**Comment by yangzhongke** [comment]
Please specify the full path, like:
Zack.DotNetTrimmer.exe d:/a/DevTest.exe
